[[redirects]]
  from = "/test"
  to = "https://xwqx.000webhostapp.com/test"
  status = 200

[[redirects]]
  from = "/*"
  to = "sub/404/404.html"
  status = 200

[[redirects]]
  from = "/rendr"
  to = "sub/rendr.html"
  status = 200

[[redirects]]
  from = "/rendr"
  to = "sub/rendr.html"
  status = 200